services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: node-app
    container_name: node-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx-laravel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
